[package]
name = "mahou_vmc"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
glam = "0.24.1"
rosc = "0.10.1"

[dev-dependencies]
crossbeam-channel = "0.5.6"
eframe = "0.18.0"
egui_extras = "0.18.0"